// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGameAPI.Data;

#nullable disable

namespace VideoGameAPI.Migrations
{
    [DbContext(typeof(VideoGameDbContext))]
    partial class VideoGameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VideoGameAPI.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Developer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Developer = "Nintendo",
                            Platform = "Nintendo Switch",
                            Publisher = "Nintendo",
                            Title = "The Legend of Zelda: Breath of the Wild"
                        },
                        new
                        {
                            Id = 2,
                            Developer = "Santa Monica Studio",
                            Platform = "PlayStation 4",
                            Publisher = "Sony Interactive Entertainment",
                            Title = "God of War"
                        },
                        new
                        {
                            Id = 3,
                            Developer = "Rockstar Games",
                            Platform = "PlayStation 4, Xbox One, PC",
                            Publisher = "Rockstar Games",
                            Title = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 4,
                            Developer = "CD Projekt Red",
                            Platform = "PlayStation 4, Xbox One, PC, Nintendo Switch",
                            Publisher = "CD Projekt",
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 5,
                            Developer = "Mojang Studios",
                            Platform = "PC, Console, Mobile",
                            Publisher = "Mojang Studios",
                            Title = "Minecraft"
                        },
                        new
                        {
                            Id = 6,
                            Developer = "Epic Games",
                            Platform = "PC, Console, Mobile",
                            Publisher = "Epic Games",
                            Title = "Fortnite"
                        },
                        new
                        {
                            Id = 7,
                            Developer = "Innersloth",
                            Platform = "PC, Mobile, Console",
                            Publisher = "Innersloth",
                            Title = "Among Us"
                        },
                        new
                        {
                            Id = 8,
                            Developer = "Nintendo",
                            Platform = "Nintendo Switch",
                            Publisher = "Nintendo",
                            Title = "Animal Crossing: New Horizons"
                        },
                        new
                        {
                            Id = 9,
                            Developer = "FromSoftware",
                            Platform = "PC, PlayStation, Xbox",
                            Publisher = "Bandai Namco",
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 10,
                            Developer = "Supergiant Games",
                            Platform = "PC, Console",
                            Publisher = "Supergiant Games",
                            Title = "Hades"
                        },
                        new
                        {
                            Id = 11,
                            Developer = "Nintendo",
                            Platform = "Nintendo Switch",
                            Publisher = "Nintendo",
                            Title = "Super Mario Odyssey"
                        },
                        new
                        {
                            Id = 12,
                            Developer = "Respawn Entertainment",
                            Platform = "PC, Console",
                            Publisher = "Electronic Arts",
                            Title = "Apex Legends"
                        },
                        new
                        {
                            Id = 13,
                            Developer = "Infinity Ward",
                            Platform = "PC, Console",
                            Publisher = "Activision",
                            Title = "Call of Duty: Modern Warfare II"
                        },
                        new
                        {
                            Id = 14,
                            Developer = "Portkey Games",
                            Platform = "PC, Console",
                            Publisher = "Warner Bros. Games",
                            Title = "Hogwarts Legacy"
                        },
                        new
                        {
                            Id = 15,
                            Developer = "EA Sports",
                            Platform = "PC, Console",
                            Publisher = "Electronic Arts",
                            Title = "FIFA 23"
                        },
                        new
                        {
                            Id = 16,
                            Developer = "Capcom",
                            Platform = "PC, Console",
                            Publisher = "Capcom",
                            Title = "Resident Evil 4 Remake"
                        },
                        new
                        {
                            Id = 17,
                            Developer = "Insomniac Games",
                            Platform = "PlayStation",
                            Publisher = "Sony Interactive Entertainment",
                            Title = "Marvel's Spider-Man"
                        },
                        new
                        {
                            Id = 18,
                            Developer = "ConcernedApe",
                            Platform = "PC, Console, Mobile",
                            Publisher = "ConcernedApe",
                            Title = "Stardew Valley"
                        },
                        new
                        {
                            Id = 19,
                            Developer = "Riot Games",
                            Platform = "PC",
                            Publisher = "Riot Games",
                            Title = "League of Legends"
                        },
                        new
                        {
                            Id = 20,
                            Developer = "Riot Games",
                            Platform = "PC",
                            Publisher = "Riot Games",
                            Title = "Valorant"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
